name: sync stars

on:
  schedule:
    - cron: '0 0 * * *' # Daily Midnight

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: checkout repo content
        uses: actions/checkout@v3 # checkout the repository content to github runner

      - name: setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          
      - name: run
        run: ./run.sh
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          RAINDROP_TOKEN: ${{ secrets.RAINDROP_TEST_TOKEN }}
          RAINDROP_COLLECTION_ID: ${{ secrets.RAINDROP_COLLECTION_ID }}

